-- 1) QUANTOS PRODUTOS TEMOS CADASTRADO NO SISTEMA QUE CUSTAM MAIS QUE 1500 DOLARES?
SELECT COUNT (ListPrice) 
FROM Production.Product
WHERE ListPrice >= 1500;

-- 2) QUANTAS PESSOAS TEMOS COM O SOBRENOME QUE INICIA COM A LETRA P?
SELECT COUNT (LastName)
FROM Person.Person
WHERE LastName LIKE 'P%';

-- 3) EM QUANTAS CIDADES ÚNICAS ESTÃO CADASTRADO NOSSOS CLIENTES?
SELECT COUNT (DISTINCT (city))
FROM Person.Address;

-- 4) QUAIS SÃO AS CIDADES ÚNICAS QUE TEMOS CADASTRADO EM NOSSO SISTEMA?
SELECT DISTINCT (city)
FROM Person.Address
ORDER BY city asc;

-- 5) QUANTOS PRODUTOS VERMELHOS TEM PREÇO ENTRE 500 A 1000 DOLARES?
SELECT COUNT (color)
FROM Production.Product
WHERE color = 'red'	and ListPrice BETWEEN 500 and 1000

-- 6) QUANTOS PRODUTOS CADASTRADOS TEM A PALAVRA 'ROAD' NO NOME DELES?
SELECT COUNT (Name)
FROM Production.Product
WHERE name LIKE '%road%';